### ISSUE TITLE
Python example expects a "libmps.so.3"

### ISSUE THREAD

**Issue by r-zachary-murray** [robol/MPSolve#10]
Downloaded and installed MPSolve 3.1.7 per the directions in the README. (including the optional 'sudo make install').  However, trying to import the mpsolve python module in the examples folder raises an error.  In Python 2.7.15 and 3.6.7 the errors are respectively:

```
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpsolve
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mpsolve.py", line 8, in <module>
    _mps = ctypes.CDLL("libmps.so.3")
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmps.so.3: cannot open shared object file: No such file or directory

```

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpsolve
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moon/mpsolve-3.1.7/examples/python/mpsolve.py", line 8, in <module>
    _mps = ctypes.CDLL("libmps.so.3")
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmps.so.3: cannot open shared object file: No such file or directory
>>> 

```

It seems like it expects a "libmps.so.3" file that isn't included in the directory. I looked into the libmps directory and couldn't find anything that looked promising.  Perhaps there's a dependency that I'm missing?

**Comment by robol** [comment]
Sorry for the late answer. The reason for this is that the python module requires libmps.so.3 to be installed and available; you might just miss a call to ldconfig if you installed the library in /usr/local, which is the default. 

When you run ./configure --prefix=/usr, which what most distributions would need to do, then everything will work as expected out of the box. 

For local development, you can just set the LD_LIBRARY_PATH environment variable to point where the library actually is; even without a make install, you will usually find it in src/libmps/.libs (unless you built the software in another directory).

It is expected that, from the examples/python folder, the command
$ LD_LIBRARY_PATH=../../src/libmps/.libs python example.py
should work.
