### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by florestan** [robol/MPSolve#12]
I got the following error during the compilation (I'm using the latest tarball)

```
Making all in mpsolve
make[3]: Entering directory `/u/math/userName/mpsolve-3.1.8/src/mpsolve'
  CXXLD    mpsolve
../../src/libmps/.libs/libmps.so: undefined reference to `operator<<(std::ostream&, __mpq_struct const*)'
collect2: error: ld returned 1 exit status
```
Any idea how to fix this ?

**Comment by robol** [comment]
On Fri, 2019-11-29 at 06:37 -0800, florestan wrote:
> Any idea how to fix this ?

My first guess is that the C++ library for GMP is missing; if this is a
Linux system, then the package is probably called libgmpxx4ldbl (this
is on Ubuntu) or similar. 

You may try to look into for something with "gmpxx"; otherwise, feel
free to provide some more detail (i.e., which operating system). 

Best, Leonardo.

**Comment by florestan** [comment]
It is a Linux system. As I have limited rights, I installed GMP locally with the conda packaging system.
When running `./configure`, I have the following message relevant to GMP:
```
checking gmp.h usability... yes
checking gmp.h presence... no
configure: WARNING: gmp.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: gmp.h: proceeding with the compiler's result
checking for gmp.h... yes
```
So I guess it detects GMP but it is not so happy about it ?

**Comment by robol** [comment]
It looks like the compiler is not happy about the GMP library installed. I suspect I cannot offer more insight without actually having access to the computer, but I would suggest trying to compile a simple program against GMP and see if that works.

**Comment by florestan** [comment]
I solved it. My GMP installation didn't contain the C++ library, like you said. I recompiled GMP with the C++ library, and the installation worked. Thanks a lot.
