### ISSUE TITLE
"no Qt platform plugin could be initialized."

### ISSUE THREAD

**Issue by GolfingSuccess** [robol/MPSolve#13]
I am on Windows 10. Whenever I try to open MPSolve, a window titled "xmpsolve" appears with the error message "This application failed to start because no Qt platform plugin could be initialized. Reinstalling this application may fix this problem." Mind you, this is after freshly installing it, so I doubt a reinstallation will do anything at all. I searched for this error online, and it turns out that it's usually caused by a mistake in the building process, not the system it's installed on. As a result, I essentially can't try out the program, and it looks very promising.

**Comment by robol** [comment]
It looks like the libraries for the Qt Windows platform were not included in the last Windows build, by mistake. You may try to run the previous version, and see if that works. As soon as I manage to perform the build once more I will update the downloads on the website.

**Comment by robol** [comment]
This should have been fixed in the latest release (3.2.1), which can be downloaded from https://numpi.dm.unipi.it/software/mpsolve/downloads. Feel free to reopen the issue if this is not the case.
