### ISSUE TITLE
Documentation for the -s option

### ISSUE THREAD

**Issue by florestan** [robol/MPSolve#14]
I couldn't find documentation for the -s option of the binary (what kind of file is expected, etc.).
Could you point me to something ?

**Comment by robol** [comment]
Il giorno lun, 02/12/2019 alle 08.50 -0800, florestan ha scritto:
> I couldn't find documentation for the -s option of the binary (what
> kind of file is expected, etc.).
> Could you point me to something ?

If I remember correctly, you need use the same format used in the files
containing the results that you can find in src/results/unisolve/*.res.

That would be a file with n lines, each of the form (real part,
imaginary part), given as floating point values. 

That is likely not described in the documentation, as you say, I will
try to update the website to report it (and I am always happy to accept
pull requests for this kind of changes).
