### ISSUE TITLE
mpcf_set_str() does not set imaginary part

### ISSUE THREAD

**Issue by femogavero** [robol/MPSolve#18]
There is probably a bug in the function mpcf_set_str(), as it seems to me it does not set the imaginary part of the complex number. As mpf_set_str() returns 0 if the provided string is a valid number, I think there should be no logical negation in the conditional statement, as it follows:

```
int
mpcf_set_str (mpcf_t c, char *sr, char *si, int base)
{
  if (mpf_set_str (mpcf_Re (c), sr, base))
    return -1;
  return mpf_set_str (mpcf_Im (c), si, base);
}
```

**Comment by robol** [comment]
Thanks, that should be fixed now (please note that until the transition to the new mpcf type will be complete, I will keep fixing both the master and mpc-rename branches).
