### ISSUE TITLE
~/MPSolve/examples/C

### ISSUE THREAD

**Issue by adammaj1** [robol/MPSolve#2]
Hi,

I have Ubuntu 16.04 LTS
After : 

git clone git://github.com/robol/MPSolve.git
Cloning into 'MPSolve'...
remote: Counting objects: 14647, done.
remote: Total 14647 (delta 0), reused 0 (delta 0), pack-reused 14647
Receiving objects: 100% (14647/14647), 23.56 MiB | 1.40 MiB/s, done.
Resolving deltas: 100% (11281/11281), done.
Checking connectivity... done.

Now in : 
~/MPSolve/examples/C$ make

gives errror : 

gcc -o mandelbrot mandelbrot.c -I../../include -DNOMPTEMP -g -O0 -lmps -lm -lgmp -lpthread -L../../src/libmps/.libs -static
In file included from mandelbrot.c:30:0:
../../include/mps/mps.h:64:20: fatal error: mps/mt.h: Nie ma takiego pliku ani katalogu
compilation terminated.
Makefile:8: polecenia dla obiektu 'mandelbrot' nie powiodły się
make: *** [mandelbrot] Błąd 1

No such file 

Adam

**Comment by robol** [comment]
This example has been not maintained for a long time, so the Makefile was using old configuration. I migrated it to the new build system. You can try to run git pull to update the source and run make again.
