### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by advanpix** [robol/MPSolve#23]
Thank you for creating the library.

I am testing pre-built Windows DLLs distributed from mpsolve homepage.

If I run following simple code, memory consumption of the process grows very fast and never drops:
```
for(int i = 0; i <= 4000000; i++)
{
       mps_context* s = mps_context_new();
       mps_context_free (s);
}
```
Eventually process gets all available memory and hangs. I guess some memory buffers are not released back to the system. 
Could you please confirm?

**Comment by advanpix** [comment]
I tested the same code on CentOS (GCC 9.2.0, GMP 6.2.0, --enable-alloca=alloca) - no memory leeks detected.
Looks like this is very much dependent of GMP compilation flags used for Windows/MSYS.

**Comment by advanpix** [comment]
Would really appreciate, if maintainers would reply something - if this issue is to be investigated, etc.

**Comment by robol** [comment]
Dear Pavel,
as the issue appears to be Windows-only it will take some more time to be looked at, I believe. The GMP and GMPXX libraries used are the ones distributed with MSYS2. If the memory leak appears just with mps_context_new() I don't think this would be GMP-related, as I don't remember any multiprecision library being allocated in this process (I might be wrong, I need to check).

In any case:
 - Could try to see if the problem is present in the most recent git version, compiled from scratch (i.e., not the DLL distributed through the website).
 - If it is, could you run something like valgrind to see if the leak is detected?

If you find the problem I am more than happy of taking a PR for this; otherwise, I will probably investigate it at some point.

**Comment by advanpix** [comment]
Thank you for your reply. 
Do you have any specific scripts to build the library under MSYS2? 

I tried compilation using the standard way - configure cannot find the pthreads library even though it is installed and included into CC/CXX variables before executing the  configure.

Overall, after testing it a bit more, I am convinced that reasons for the mem. leak are somehow related to pthreads and the way it   is compiled for Windows or/and memory allocations. Some TLS caches needs to be freed, or temporal variables are allocated on the heap instead of the stack allocations (and therefore never freed) or something like that.

**Comment by robol** [comment]
You can have a look at tools/msys2-make.sh, which i used to generate all the Windows files starting from the tarball (building from the tarball is slightly easier than from git, as some files are pre-generated, and you don't need stuff such as flex / bison). The script takes the tarball as argument. 

Even without running the script, you may want to look at it for the required dependencies and to see the steps.

**Comment by advanpix** [comment]
Ok, thanks, will do this.
You do not run autoconf tools in the script. Does it support building from the git master sources (compressed as tar.gz)?

**Comment by robol** [comment]
I never tested the script with the master branch; I would guess that adding a call to autogen.sh and making sure that flex / bison & automake are installed should be enough, but I've never tested it.

**Comment by advanpix** [comment]
I have re-built the most recent libmps from scratch with the MSYS2 (gcc 10.2.0) - unfortunately memleak is still present. 
I am not sure if valgrind exists for MSYS2 (nor I have experience with it). So, unfortunately MPSolve is unusable under Windows now.

Btw, I managed to build the MPsolve using the native compilers on Windows - MSVC (with properly ported GMP and PTHREADS), memleak is still present. 

Earlier I reported that no memleak was detected on CentOS, but now I have doubts about it. Maybe compiler optimized away some unused code  on CentOS and therefore no memleak was detected.

Will stick to O(n^3) eigensolver of companion matrix for now....

**Comment by advanpix** [comment]
I couldn't stop but started to study the source code of the library more deeply.

One source of memory leaks is that (many) mutex & condition variables are not freed with `pthread_mutex_destroy` and `pthread_cond_destroy` functions. For example, you do the `pthread_mutex_init (&thread->busy_mutex, NULL)` for each thread, but there is no corresponding `pthread_mutex_destroy`. There are many such cases, in total, there are 27 calls to `pthread_mutex_init` but there is only 4 calls to `pthread_mutex_destroy` in the source code. Similar situation is with pthread conditions.

The memleaks related to pthreads are more apparent on Windows, because there are a lot of data structures used to emulate them on top of native Windows threads. We can see fast memory growth. On *NIX pthreads have very little data overhead and leaks are not easy to detect (I guess).

In general, if I disable calls to `mps_thread_pool_new/free` my program show no signs of leaks. Therefore, memory leaks are related to multi-threading code. Could you please these ones?

Thank you.

**Comment by robol** [comment]
Great, that's a good suggestion, I will look into it. Concerning static global variables, what are you referring specifically? If I remember correctly, everything was rearranged to live inside mps_context instances (in MPSolve 2.x, all the data was stored in global variables).

**Comment by advanpix** [comment]
mpsolve-3.2.1\src\libmps\common\context.c:

```
static mps_context ** context_factory = NULL;
static int context_factory_size = 0;
static pthread_mutex_t context_factory_mutex = PTHREAD_MUTEX_INITIALIZER;
```

mpsolve-3.2.1\src\libmps\system\threading.c:
```
static mps_thread_pool * system_thread_pool = NULL;
static pthread_mutex_t system_thread_pool_lock = PTHREAD_MUTEX_INITIALIZER;
```

There are other places (these are just what I have seen). It is better to wrap all of these inside function.

**Comment by advanpix** [comment]
I have just added calls to `pthread_mutex_destroy` at several (obvious) places. Memory leaks have reduced considerable. So, this is confirmation of the situation.

**Comment by robol** [comment]
Sounds great; I started working on this in the branch fix-memleak; working on Linux I still can not see the memory increase that you describe, but I'll fix the most apparent problems and then test it on Windows. Any feedback is appreciated!

**Comment by advanpix** [comment]
Mutexes are system-level objects and Linux might allocate them in the kernel, not in the process memory space. Therefore you cannot see the memory growth for the particular process.

Let me know when I can start testing the fixed version.

**Comment by robol** [comment]
I tested the new version on Windows and now the memory usage is stable; feel free to try it out (it's in the fix-memleak branch). I've also removed the global variables related to the context_factory there were not used anymore. I still have to investigate the other.

**Comment by advanpix** [comment]
I have tested the new version - no memory leaks can be reproduced anymore (in simple code from my first comment).  Now I
can use MPSolve in my code. Thank you for the quick fixes!

FYI, I see memory is slowly leaking somewhere in the function `mps_mpsolve`. If I run the following code in a loop - memory is growing. Parameters I tried: n=100..500, digits=15, nthreads=8 with the same set of coefficients (coeffs) generated beforehand.

```
    mps_context* s = mps_context_new();
    mps_polynomial* poly = (mps_polynomial*)mps_monomial_poly_new(s,n);

    for(int i = 0; i <= n; i++)
        mps_monomial_poly_set_coefficient_d(s,(mps_monomial_poly*)poly,i,coeffs[i],0.0);

    mps_context_set_input_poly            (s, poly);
    mps_context_set_output_prec           (s, std::ceil(digits * LOG2_10));
    mps_context_set_output_goal           (s, MPS_OUTPUT_GOAL_APPROXIMATE);
    mps_context_select_algorithm          (s, MPS_ALGORITHM_STANDARD_MPSOLVE);
    mps_thread_pool_set_concurrency_limit (s, NULL, nthreads);

    mps_mpsolve(s);

    mps_polynomial_free (s, poly);
    mps_context_free (s);
```

Memory is not leaking if I comment out the `mps_mpsolve`.  This is not crucial for my application, but I think it worth checking at least in future.

**Comment by robol** [comment]
Great, thanks. I'll open a new issue to track this one.
