### ISSUE TITLE
insatlling:

### ISSUE THREAD

**Issue by adammaj1** [robol/MPSolve#3]
Hi 
I try to compile mpsolve ( from git repo)
 so: 
make

/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --no-create --no-recursion
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... no
checking for mawk... mawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking for gfortran... gfortran
checking whether we are using the GNU Fortran compiler... yes
checking whether gfortran accepts -g... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gfortran option to produce PIC... -fPIC
checking if gfortran PIC flag -fPIC works... yes
checking if gfortran static flag -static works... yes
checking if gfortran supports -c -o file.o... yes
checking if gfortran supports -c -o file.o... (cached) yes
checking whether the gfortran linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking dependency style of g++... gcc3
checking for gcc option to accept ISO C99... none needed
checking for bison... no
checking for byacc... byacc
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking for inline... inline
checking whether C compiler accepts -fcx-limited-range... yes
checking whether C compiler accepts -fno-math-errno... yes
checking whether C compiler accepts -fomit-frame-pointer... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for size_t... yes
checking for error_at_line... yes
checking for memset... yes
checking for modf... yes
checking for pow... no
checking for sqrt... no
checking for strchr... yes
checking for Win32 platform... no
checking for __attribute__((visibility("hidden")))... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -pthread is sufficient with -shared... yes
checking whether what we have so far is sufficient with -nostdlib... yes
checking if sysconf(_SC_NPROCESSORS_ONLN) is supported... yes
checking for malloc in -ltcmalloc_minimal... no
checking for snprintf... yes
checking for vsnprintf... yes
checking for working snprintf... yes
checking for working vsnprintf... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for getline... yes
checking for strndup... yes
checking if C99 complex.h is supported from the C++ compiler... no
checking for pow in -lm... yes
checking for __gmpz_init2 in -lgmp... yes
checking for main in -lgmpxx... yes
checking gmp.h usability... yes
checking gmp.h presence... yes
checking for gmp.h... yes
checking for mpfr_init in -lmpfr... yes
checking mpfr.h usability... yes
checking mpfr.h presence... yes
checking for mpfr.h... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for CHECK... no
checking for GTK... yes
checking for CAIRO... yes
checking for QT4... yes
checking for QT5... no
checking for uic-qt4... uic-qt4
checking for moc-qt4... moc-qt4
checking for rcc-qt4... no
checking for rcc... rcc
checking for mkoctfile... no
checking for octave... no
checking for a valid mex compiler... 
checking for a Python interpreter with version >= 2.3... python
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/dist-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/dist-packages
checking for python2.7-config... no
checking for python-config... no
configure: WARNING: cannot find python-config for /usr/bin/python.
checking for doxygen... no
configure: WARNING: Doxygen not found, documentation will not be generated
checking that generated files are newer than configure... done
configure: creating ./config.status

MPSolve configuration:

        Source location:	.
	Pthread CFLAGS:		-pthread
        C compiler:		gcc
	CFLAGS:			-D_REENTRANT -Wall -DMPS_USE_BUILTIN_COMPLEX  -DNICE_DEBUG -fcx-limited-range -fno-math-errno -fomit-frame-pointer -D_MPS_PRIVATE
        LDFLAGS:                 
	Additional CFLAGS:	-g -O2
        Debug enabled:		yes
        Check enabled:		no
	Octave module:		no
	MATLAB (tm) module:	no
	Graphical UI:		yes
	Python module:          no

Type 'make' to compile MPSolve, and then make install
to install the binaries, the library and the headers
system-wide.

 /bin/bash ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating include/mps/Makefile
config.status: creating include/mps/private/Makefile
config.status: creating examples/Makefile
config.status: creating examples/fortran/Makefile
config.status: creating examples/octave/Makefile
config.status: creating examples/matlab/Makefile
config.status: creating examples/gtk/Makefile
config.status: creating examples/python/Makefile
config.status: creating examples/python/tests/Makefile
config.status: creating examples/mandelbrot-solver/Makefile
config.status: creating examples/mandelbrot-solver/mandelbrot-solver.1
config.status: creating examples/quadratic-solver/Makefile
config.status: creating examples/quadratic-solver/quadratic-solver.1
config.status: creating include/mps/mt.h
config.status: creating src/Makefile
config.status: creating src/mpsolve/Makefile
config.status: creating src/mpsolve/mpsolve.1
config.status: creating src/libmps/Makefile
config.status: creating src/tests/Makefile
config.status: creating src/xmpsolve/Makefile
config.status: creating src/xmpsolve/xmpsolve.desktop
config.status: creating src/xmpsolve/xmpsolve.1
config.status: creating doc/Makefile
config.status: creating doc/Doxyfile
config.status: creating mime/Makefile
config.status: creating config.h
config.status: executing libtool commands
config.status: executing depfiles commands
make  all-recursive
make[1]: Wejście do katalogu '/home/a/MPSolve'
Making all in include
make[2]: Wejście do katalogu '/home/a/MPSolve/include'
Making all in mps
make[3]: Wejście do katalogu '/home/a/MPSolve/include/mps'
Making all in private
make[4]: Wejście do katalogu '/home/a/MPSolve/include/mps/private'
make[4]: Nie ma nic do zrobienia w 'all'.
make[4]: Opuszczenie katalogu '/home/a/MPSolve/include/mps/private'
make[4]: Wejście do katalogu '/home/a/MPSolve/include/mps'
make[4]: Nie ma nic do zrobienia w 'all-am'.
make[4]: Opuszczenie katalogu '/home/a/MPSolve/include/mps'
make[3]: Opuszczenie katalogu '/home/a/MPSolve/include/mps'
make[3]: Wejście do katalogu '/home/a/MPSolve/include'
make[3]: Nie ma nic do zrobienia w 'all-am'.
make[3]: Opuszczenie katalogu '/home/a/MPSolve/include'
make[2]: Opuszczenie katalogu '/home/a/MPSolve/include'
Making all in src
make[2]: Wejście do katalogu '/home/a/MPSolve/src'
Making all in libmps
make[3]: Wejście do katalogu '/home/a/MPSolve/src/libmps'
  YACC     monomial/yacc-parser.c
byacc: e - line 6 of "/home/a/MPSolve/src/libmps/monomial/yacc-parser.y", syntax error
%debug
^
Makefile:1900: polecenia dla obiektu 'monomial/yacc-parser.c' nie powiodły się
make[3]: *** [monomial/yacc-parser.c] Błąd 1
make[3]: Opuszczenie katalogu '/home/a/MPSolve/src/libmps'
Makefile:429: polecenia dla obiektu 'all-recursive' nie powiodły się
make[2]: *** [all-recursive] Błąd 1
make[2]: Opuszczenie katalogu '/home/a/MPSolve/src'
Makefile:486: polecenia dla obiektu 'all-recursive' nie powiodły się
make[1]: *** [all-recursive] Błąd 1
make[1]: Opuszczenie katalogu '/home/a/MPSolve'
Makefile:418: polecenia dla obiektu 'all' nie powiodły się
make: *** [all] Błąd 2

What should I do ?

**Comment by robol** [comment]
The %debug line is only supported by bison and not by byacc, that you are using to compile the parser. However, it is not important at all, so I removed it. You can try to run "git pull" to update the source code and run make again. Let me know if it doesn't work.
