### ISSUE TITLE
Wrong algorithm in complex diision

### ISSUE THREAD

**Issue by kagalenko-m-b** [robol/MPSolve#9]
Function mpc_ui_div() is wrong, it divides integer numerator separately by imaginary and real part of denominator.

From the file src/libmps/floating-point/mpc.c
```C
void
mpc_ui_div (mpc_t rc, unsigned long int i, mpc_t c)
{
  mpf_ui_div (mpc_Re (rc), i, mpc_Re (c));
  mpf_ui_div (mpc_Im (rc), i, mpc_Im (c));
}
```

**Comment by kagalenko-m-b** [comment]
Also, this definition from mpc.h will not compile:
```C
#define mpc_add_eq_f(C, R, F)   mpc_add_f (C, C, R, F)
```
because it's incompatible with earlier declaration
```C
void mpc_add_f (mpc_t rc, mpc_t c, mpf_t f);
```

**Comment by robol** [comment]
Thanks for noticing this. These functions are not used inside MPSolve, so I will either fix them or remove them.
